/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfac;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelDAO.ConsultaDAO;
import java.sql.SQLException;
import java.sql.ResultSet;
import model.produtos;

/**
 *
 * @author User
 */
public class jifConsultaProduto extends javax.swing.JInternalFrame{
produtos objpro = new produtos();
    /**
     * Creates new form jifConsultaTransp
     */
    public jifConsultaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlConsulta = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox<>();
        jtInfo = new javax.swing.JTextField();
        jlInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jbPesquisar = new javax.swing.JButton();
        jbCap = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta de Produtos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jlConsulta.setText("Consulta por:");

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod.", "Descrição", "Grupo", "Linha", "Material", "Dureza" }));
        jcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoActionPerformed(evt);
            }
        });

        jtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInfoActionPerformed(evt);
            }
        });

        jlInfo.setText("Digite a informação:");

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Descrição", "Grupo", "Linha", "Material", "Dureza"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTabela.setAutoscrolls(false);
        jTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabela.setShowGrid(false);
        jScrollPane1.setViewportView(jTabela);

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbCap.setText("Capturar");
        jbCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCapActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jbCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConsulta)
                    .addComponent(jlInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcTipo, jtInfo});

        setBounds(250, 20, 888, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        jPrincipal.consultaProduto=true;
                
        DefaultTableModel mp1 = (DefaultTableModel) jTabela.getModel();
        
        int l = mp1.getRowCount(); //conta as linhas da tabela
        
        if(l>0)
        {
            while(l>0){
                ((DefaultTableModel) jTabela.getModel()).removeRow(l-1); // primeira linha tem valor 0
                l--;
            } //fim While
            
        } //fim do if - verifica se tem alguma info. na tabela
        
        try {
            
            
            //sem atgumento na pesquisa
            ResultSet rs = ConsultaDAO.carregaTabelaProdutos();
            
            //instancia o objeto mp da classe DefaultTableModel
            DefaultTableModel mp = (DefaultTableModel) jTabela.getModel();
            
            while(rs.next()){
                
                //coleta os dados da linha no banco de dados
                String Coluna0=rs.getString("id_produtos").toString().trim();
                String Coluna1=rs.getString("pro_descri").toString().trim();
                String Coluna2=rs.getString("pro_grupo").toString().trim();
                String Coluna3=rs.getString("pro_linha").toString().trim();
                String Coluna4=rs.getString("pro_material").toString().trim();
                String Coluna5=rs.getString("pro_dureza").toString().trim();
                

                        //preenche a linha da JTable e volta para o while até terminar as linhas contidas
                        //na tabela do banco
                        mp.addRow(new String[]{Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
        }
        
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+ erro, "Preencher Item", 2);
        } 
        
       
        tamanhocoluna();
        jTabela.setAutoCreateRowSorter(true); //ordena as linhas ao clicar na coluna
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        jPrincipal.consultaProduto=false;
        
        dispose();
    }//GEN-LAST:event_formInternalFrameClosed

    private void jtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtInfoActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:   
        
        DefaultTableModel mp1 = (DefaultTableModel) jTabela.getModel();
      
      int l=mp1.getRowCount();
      
      
      if(l>0){
          while(l>0){
                ((DefaultTableModel) jTabela.getModel()).removeRow(l-1); // primeira linha tem valor 0
                l--;
            } //fim While
            
        } //fim do if - verifica se tem alguma info. na tabela
      
      //fim limpa a tabela
        
        String tipo="";
      String escolha=jcTipo.getSelectedItem().toString().trim();
      
            if(escolha.equals("Cod.")){
          tipo=" "+"id_produtos";
      }     if(escolha.equals("Descrição")){
          tipo=" "+"pro_descri";
      }    if(escolha.equals("Grupo")){
          tipo=" "+"pro_grupo";
      }     if(escolha.equals("Linha")){
          tipo=" "+"pro_linha";
      }     if(escolha.equals("Material")){
          tipo=" "+"pro_material";
      }     if(escolha.equals("Dureza")){
          tipo=" "+"pro_dureza";
      }         
      String arg=jtInfo.getText();
      
      

        
        
      try{
          ResultSet rs = ConsultaDAO.carregaTelaProdutos(tipo, arg);
          
           DefaultTableModel mp = (DefaultTableModel) jTabela.getModel();
            
            while(rs.next()){
                
                //coleta os dados da linha no banco de dados
                String Coluna0=rs.getString("id_produtos").toString().trim(); 
                String Coluna1=rs.getString("pro_descri").toString().trim();
                String Coluna2=rs.getString("pro_grupo").toString().trim();
                String Coluna3=rs.getString("pro_linha").toString().trim();
                String Coluna4=rs.getString("pro_material").toString().trim();
                String Coluna5=rs.getString("pro_dureza").toString().trim();
                                
                                
          mp.addRow(new String[]{Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
          
          
          
      }
        
      } catch (SQLException error){
          JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+ error, "Preencher Item", 2);
      }
      
      tamanhocoluna();
        jTabela.setAutoCreateRowSorter(true); //ordena as linhas ao clicar na coluna
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        jPrincipal.consultaProduto=false;
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCapActionPerformed
        // TODO add your handling code here:                     
        int row =jTabela.getSelectedRow();
        
        if (jPrincipal.fichao==true){
            objpro.setPro_descri(String.valueOf(jTabela.getValueAt(row, 1).toString().trim()));
            jifFichao.recebeProduto(objpro);
            
        } else {
            objpro.setId_produtos(Integer.parseInt(jTabela.getValueAt(row, 0).toString().trim()));
            jifProduto.recebeidProdutos(objpro);
        }
        dispose(); 
    }//GEN-LAST:event_jbCapActionPerformed

    private void jcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JButton jbCap;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JLabel jlConsulta;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JTextField jtInfo;
    // End of variables declaration//GEN-END:variables
public void tamanhocoluna(){
jTabela.getColumnModel().getColumn(0).setPreferredWidth(70);
jTabela.getColumnModel().getColumn(1).setPreferredWidth(250);
jTabela.getColumnModel().getColumn(2).setPreferredWidth(170);
jTabela.getColumnModel().getColumn(3).setPreferredWidth(170);
jTabela.getColumnModel().getColumn(4).setPreferredWidth(90);
jTabela.getColumnModel().getColumn(5).setPreferredWidth(90);
}//dimensionar tabela
   

}