/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfac;

import connection.ConsultaCNPJController;
import connection.PessoaJuridica;
import Jm.JMascara;
import java.net.URL;
import javax.swing.JOptionPane;
import model.transportadora;
import modelDAO.ExcluirDAO;
import modelDAO.IncluirEditarDAO;
import modelDAO.PesquisaDAO;
import java.sql.SQLException;
import java.util.Iterator;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

/**
 *
 * @author User
 */
public class jifTransportadora extends javax.swing.JInternalFrame {
    
    int acao;
    int status;
    
     private ConsultaCNPJController controller;


    transportadora objtra = new transportadora();
    
    IncluirEditarDAO IEDAO;    
    ExcluirDAO EXDAO;
    PesquisaDAO PESDAO;
    /**
     * Creates new form Transportadora
     */
    public jifTransportadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAtividade = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlRazaoS = new javax.swing.JLabel();
        jtRazaoS = new javax.swing.JTextField();
        jlApelido = new javax.swing.JLabel();
        jtApelido = new javax.swing.JTextField();
        jbBuscarT = new javax.swing.JButton();
        jlCod = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();
        jliE = new javax.swing.JLabel();
        jtiE = new javax.swing.JTextField();
        jlCnpj = new javax.swing.JLabel();
        jrAtivo = new javax.swing.JRadioButton();
        jrInativo = new javax.swing.JRadioButton();
        jlCodIbge = new javax.swing.JLabel();
        jtCodIbge = new javax.swing.JTextField();
        jtPlat = new javax.swing.JLabel();
        jcPlat = new javax.swing.JComboBox<>();
        jlEmpi = new javax.swing.JLabel();
        jcEmpi = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jlEnd = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jbCep = new javax.swing.JButton();
        jlCidade = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jlRua = new javax.swing.JLabel();
        jtCompl = new javax.swing.JTextField();
        jlCompl = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jlBairro = new javax.swing.JLabel();
        jtNum = new javax.swing.JTextField();
        jlNum = new javax.swing.JLabel();
        jtCnpj = new javax.swing.JFormattedTextField();
        jtCep = new javax.swing.JFormattedTextField();
        jtCidade = new javax.swing.JTextField();
        jcUf = new javax.swing.JComboBox<>();
        jcPessoa = new javax.swing.JComboBox<>();
        jlPessoa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlInfoCon = new javax.swing.JLabel();
        jlTelCel = new javax.swing.JLabel();
        jtTelCel = new javax.swing.JFormattedTextField();
        jlTelFixo = new javax.swing.JLabel();
        jtTelFixo = new javax.swing.JFormattedTextField();
        jlEmpresa = new javax.swing.JLabel();
        jlEmailCon = new javax.swing.JLabel();
        jtMailCon = new javax.swing.JTextField();
        jlEndWeb = new javax.swing.JLabel();
        jtEndWeb = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlVeiculo = new javax.swing.JLabel();
        jlveiCon = new javax.swing.JLabel();
        jtNomeCon = new javax.swing.JTextField();
        jtRntrc = new javax.swing.JTextField();
        jlrntrc = new javax.swing.JLabel();
        jtChapaV = new javax.swing.JTextField();
        jtTelCon = new javax.swing.JTextField();
        jlveiChapa = new javax.swing.JLabel();
        jlveiTel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jbCnpj = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Transportadora");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jlRazaoS.setText("Razão Social");

        jtRazaoS.setEnabled(false);
        jtRazaoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRazaoSActionPerformed(evt);
            }
        });

        jlApelido.setText("Apelido");

        jtApelido.setEnabled(false);

        jbBuscarT.setText("...");
        jbBuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarTActionPerformed(evt);
            }
        });

        jlCod.setText("Cod.");

        jliE.setText("Inscrição Estadual");

        jtiE.setEnabled(false);
        jtiE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtiEKeyTyped(evt);
            }
        });

        jlCnpj.setText("CNPJ");

        jbAtividade.add(jrAtivo);
        jrAtivo.setText("Ativo");
        jrAtivo.setEnabled(false);
        jrAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAtivoActionPerformed(evt);
            }
        });

        jbAtividade.add(jrInativo);
        jrInativo.setText("Inativo");
        jrInativo.setEnabled(false);
        jrInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrInativoActionPerformed(evt);
            }
        });

        jlCodIbge.setText("Cod. IBGE");

        jtCodIbge.setEnabled(false);
        jtCodIbge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodIbgeActionPerformed(evt);
            }
        });
        jtCodIbge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCodIbgeKeyTyped(evt);
            }
        });

        jtPlat.setText("Plataforma");

        jcPlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SIM", "NÃO" }));
        jcPlat.setEnabled(false);

        jlEmpi.setText("Empilhadeira");

        jcEmpi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SIM", "NÃO" }));
        jcEmpi.setEnabled(false);
        jcEmpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEmpiActionPerformed(evt);
            }
        });

        jlEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlEnd.setText("Endereço:");

        jlCep.setText("CEP");

        jlEstado.setText("UF");

        jbCep.setText("jButton1");
        jbCep.setEnabled(false);
        jbCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCepActionPerformed(evt);
            }
        });

        jlCidade.setText("Cidade");

        jtRua.setEnabled(false);
        jtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaActionPerformed(evt);
            }
        });

        jlRua.setText("Logradouro");

        jtCompl.setEnabled(false);
        jtCompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComplActionPerformed(evt);
            }
        });

        jlCompl.setText("Complemento*");

        jtBairro.setEnabled(false);
        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });

        jlBairro.setText("Bairro");

        jtNum.setEnabled(false);
        jtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumActionPerformed(evt);
            }
        });

        jlNum.setText("N°");

        jtCnpj.setEnabled(false);
        jtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCnpjActionPerformed(evt);
            }
        });
        jtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCnpjKeyReleased(evt);
            }
        });

        jtCep.setEnabled(false);
        jtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCepKeyReleased(evt);
            }
        });

        jtCidade.setEnabled(false);
        jtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeActionPerformed(evt);
            }
        });

        jcUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcUf.setEnabled(false);

        jcPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "FÍSICA", "JURÍDICA" }));
        jcPessoa.setEnabled(false);
        jcPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPessoaActionPerformed(evt);
            }
        });

        jlPessoa.setText("Pessoa");

        jlInfoCon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlInfoCon.setText("Informações de Contato: ");

        jlTelCel.setText("Telefone Celular");

        jtTelCel.setEnabled(false);
        jtTelCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelCelKeyReleased(evt);
            }
        });

        jlTelFixo.setText("Telefone Fixo");

        jtTelFixo.setEnabled(false);
        jtTelFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelFixoKeyReleased(evt);
            }
        });

        jlEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlEmpresa.setText("Empresa");

        jlEmailCon.setText("E-mail Contato");

        jtMailCon.setEnabled(false);

        jlEndWeb.setText("End. Web");

        jtEndWeb.setEnabled(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlVeiculo.setText("Veículo");

        jlveiCon.setText("Nome (Contato)");

        jtNomeCon.setEnabled(false);
        jtNomeCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeConActionPerformed(evt);
            }
        });

        jtRntrc.setEnabled(false);
        jtRntrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRntrcActionPerformed(evt);
            }
        });

        jlrntrc.setText("RNTRC");

        jtChapaV.setEnabled(false);
        jtChapaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtChapaVActionPerformed(evt);
            }
        });

        jtTelCon.setEnabled(false);
        jtTelCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelConActionPerformed(evt);
            }
        });
        jtTelCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelConKeyReleased(evt);
            }
        });

        jlveiChapa.setText("Chapa Veículo");

        jlveiTel.setText("Telefone de Contato");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlInfoCon)
                    .addComponent(jlEmpresa)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlEndWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtMailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlVeiculo)
                    .addComponent(jtNomeCon)
                    .addComponent(jtRntrc)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlveiCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlrntrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtChapaV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlveiChapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlveiTel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtChapaV, jtNomeCon, jtRntrc, jtTelCon});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtEndWeb, jtMailCon});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlInfoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmpresa)
                            .addComponent(jlVeiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlTelCel)
                                    .addComponent(jlEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtMailCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlTelFixo)
                                    .addComponent(jlEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlveiCon)
                                    .addComponent(jlveiTel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtNomeCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtTelCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlrntrc)
                                    .addComponent(jlveiChapa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtRntrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtChapaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(17, 17, 17))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtChapaV, jtEndWeb, jtMailCon, jtNomeCon, jtRntrc, jtTelCel, jtTelCon, jtTelFixo});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlEmailCon, jlEndWeb, jlTelCel, jlTelFixo, jlrntrc, jlveiChapa, jlveiCon, jlveiTel});

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbCnpj.setText("...");
        jbCnpj.setEnabled(false);
        jbCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jlRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))
                            .addComponent(jSeparator4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlEnd)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlCep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlRua, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jcUf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jlBairro)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtiE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jliE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jcPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcPlat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jcEmpi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlEmpi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrAtivo)
                                            .addComponent(jrInativo)))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addGap(20, 20, 20)
                        .addComponent(jbSalvar)
                        .addGap(20, 20, 20)
                        .addComponent(jbEditar)
                        .addGap(20, 20, 20)
                        .addComponent(jbExcluir)
                        .addGap(20, 20, 20)
                        .addComponent(jbCancelar)
                        .addGap(20, 20, 20)
                        .addComponent(jbSair)
                        .addGap(100, 100, 100))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcEmpi, jcPessoa, jcPlat});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancelar, jbEditar, jbExcluir, jbNovo, jbSair, jbSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbBuscarT, jbCnpj});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jlEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlRazaoS)
                                .addComponent(jlCnpj))
                            .addComponent(jlCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlApelido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrInativo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtPlat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jliE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlEmpi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcEmpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlEnd)
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNum)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlRua)
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCidade)
                                .addGap(5, 5, 5)
                                .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlCodIbge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCep)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlBairro)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCompl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCep, jcUf, jtBairro, jtCep, jtCidade, jtCodIbge, jtCompl, jtNum, jtRua});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlBairro, jlCep, jlCidade, jlCompl, jlEnd, jlEstado, jlNum, jlRua});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcEmpi, jcPessoa, jcPlat, jtApelido, jtCnpj, jtCod, jtRazaoS, jtiE});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlApelido, jlCnpj, jlCod, jlEmpi, jlPessoa, jlRazaoS, jliE, jtPlat});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCancelar, jbEditar, jbExcluir, jbNovo, jbSair, jbSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbBuscarT, jbCnpj});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(300, 20, 754, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void jtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumActionPerformed

    }//GEN-LAST:event_jtNumActionPerformed

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed

    }//GEN-LAST:event_jtBairroActionPerformed

    private void jtComplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComplActionPerformed

    }//GEN-LAST:event_jtComplActionPerformed

    private void jtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaActionPerformed

    }//GEN-LAST:event_jtRuaActionPerformed

    private void jcCIdadeT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCIdadeT1ActionPerformed

    }//GEN-LAST:event_jcCIdadeT1ActionPerformed

    private void jcPaisT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPaisT1ActionPerformed

    }//GEN-LAST:event_jcPaisT1ActionPerformed

    private void jbCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCepActionPerformed
    buscarCep(JMascara.GetJmascaraLimpar(jtCep.getText()));
    }//GEN-LAST:event_jbCepActionPerformed

    private void jcEstadoT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstadoT1ActionPerformed

    }//GEN-LAST:event_jcEstadoT1ActionPerformed

    private void jcEmpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEmpiActionPerformed

    }//GEN-LAST:event_jcEmpiActionPerformed

    private void jtCodIbgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodIbgeActionPerformed

    }//GEN-LAST:event_jtCodIbgeActionPerformed

    private void jrInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrInativoActionPerformed

    }//GEN-LAST:event_jrInativoActionPerformed

    private void jrAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAtivoActionPerformed

    }//GEN-LAST:event_jrAtivoActionPerformed

    private void jbBuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarTActionPerformed
 objtra = new transportadora();
 
        if(jtCod.getText().isEmpty()){
            
            jifConsultaTransp objconsulta = new jifConsultaTransp();
            jPrincipal.jTela.add(objconsulta);
            objconsulta.setVisible(true);
            jPrincipal.jTela.setComponentZOrder(objconsulta, 0);
            
        } else {
            objtra.setId_transportadora(Integer.parseInt(jtCod.getText()));
            
            PESDAO = new PesquisaDAO();
            
            try {
                
                if(PESDAO.PesquisarTelaTransportadora(objtra)){
                    if ((objtra != null))
                    {
                        pesquisaTransportadora();
                        
                    }
                }
            } catch (SQLException erro){
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar " + erro.getMessage());
            }
        }
            
    }//GEN-LAST:event_jbBuscarTActionPerformed

    private void jtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCnpjActionPerformed

    private void jtRazaoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRazaoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRazaoSActionPerformed

    private void jcPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPessoaActionPerformed

    private void jtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeActionPerformed

    private void jtNomeConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeConActionPerformed

    private void jtRntrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRntrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRntrcActionPerformed

    private void jtChapaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtChapaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtChapaVActionPerformed

    private void jtTelConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelConActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed

     acao=1;
        
        novo();

    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        
        if (jrAtivo.isSelected())
                {
         status=1;
     } 
     if (jrInativo.isSelected()){
         status=0;
     }
     
     int Cod;
     objtra = new transportadora();
     preencher_objetos();
     
     try {
         
         IEDAO = new IncluirEditarDAO();
         
            if(acao==1){
                
                salvar();

    
                Cod=IEDAO.IncluirTransportadora(objtra);
                    jtCod.setText(String.valueOf(Cod));
                    JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
            }
         
     }catch(SQLException error){
         JOptionPane.showMessageDialog(this, "Erro ao salvar: " + error.getMessage());  
          cancelar();
         
     }
     if(acao==2) {
        salvar();

        
        objtra.setId_transportadora(Integer.parseInt(jtCod.getText()));
        
           try {
               if(IEDAO.EditarTransportadora(objtra)){
                   
                   JOptionPane.showMessageDialog(this, "Alterado com Sucesso!");
                   
                   
               }  } catch (SQLException ex) {
               System.err.println("Erro: "+ ex);
           }
        
     }
             
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed

     acao=2; 
     editar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if(jtCod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o Código! ");
        }else{
            int codigo=Integer.parseInt(jtCod.getText());
            
            EXDAO = new ExcluirDAO();
    
            try {
                if (JOptionPane.showConfirmDialog(this, "Confirmar Exclusão? ", "Confirmação",
                        JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_NO_OPTION)
                    

                        if (EXDAO.ExcluirTransportadora(codigo)) {
                            JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
                            cancelar();
                            
                        } else {
                            
                            JOptionPane.showMessageDialog(this, "Erro ao excluir o registro! ");
                            
                        } else {
                    
                    JOptionPane.showMessageDialog(this, "Operação cancelada! ");
                    cancelar();
                    
                    }
                        
                } catch (SQLException error) {
                     JOptionPane.showMessageDialog(this, "Erro: Exclusão Não REalizada!" + error.getMessage());
                }
                  
        }
       
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        jPrincipal.transportadora=false;
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        jPrincipal.transportadora=true;
            
            jrAtivo.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
        jPrincipal.transportadora=false;
           dispose();
    }//GEN-LAST:event_formInternalFrameClosed

    private void jtCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCnpjKeyReleased
        // TODO add your handling code here:
         jtCnpj.setText(JMascara.GetJmascaraCpfCnpj(jtCnpj.getText()));
    }//GEN-LAST:event_jtCnpjKeyReleased

    private void jtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCepKeyReleased
        // TODO add your handling code here:
        
        jtCep.setText(JMascara.GetJmascaraCep(jtCep.getText()));

        if (jtCep.getText().length() == 8)
        {
            buscarCep(jtCep.getText());
        }
    }//GEN-LAST:event_jtCepKeyReleased

    private void jtTelFixoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelFixoKeyReleased
        // TODO add your handling code here:
        jtTelFixo.setText(JMascara.GetJmascaraFone(jtTelFixo.getText()));
    }//GEN-LAST:event_jtTelFixoKeyReleased

    private void jtTelCelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelCelKeyReleased
        // TODO add your handling code here:
        
        jtTelCel.setText(JMascara.GetJmascaraFone(jtTelCel.getText()));
    }//GEN-LAST:event_jtTelCelKeyReleased

    private void jtTelConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelConKeyReleased
        // TODO add your handling code here:
        
        jtTelCon.setText(JMascara.GetJmascaraFone(jtTelCon.getText()));
    }//GEN-LAST:event_jtTelConKeyReleased

    private void jbCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCnpjActionPerformed
        // TODO add your handling code here:
        
        buscarCNPJ();
    }//GEN-LAST:event_jbCnpjActionPerformed

    private void jtiEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtiEKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}
    }//GEN-LAST:event_jtiEKeyTyped

    private void jtCodIbgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodIbgeKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();
}
    }//GEN-LAST:event_jtCodIbgeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.ButtonGroup jbAtividade;
    private static javax.swing.JButton jbBuscarT;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCep;
    private javax.swing.JButton jbCnpj;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcEmpi;
    private javax.swing.JComboBox<String> jcPessoa;
    private javax.swing.JComboBox<String> jcPlat;
    private javax.swing.JComboBox<String> jcUf;
    private javax.swing.JLabel jlApelido;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCnpj;
    private javax.swing.JLabel jlCod;
    private javax.swing.JLabel jlCodIbge;
    private javax.swing.JLabel jlCompl;
    private javax.swing.JLabel jlEmailCon;
    private javax.swing.JLabel jlEmpi;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlEnd;
    private javax.swing.JLabel jlEndWeb;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlInfoCon;
    private javax.swing.JLabel jlNum;
    private javax.swing.JLabel jlPessoa;
    private javax.swing.JLabel jlRazaoS;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlTelCel;
    private javax.swing.JLabel jlTelFixo;
    private javax.swing.JLabel jlVeiculo;
    private javax.swing.JLabel jliE;
    private javax.swing.JLabel jlrntrc;
    private javax.swing.JLabel jlveiChapa;
    private javax.swing.JLabel jlveiCon;
    private javax.swing.JLabel jlveiTel;
    private javax.swing.JRadioButton jrAtivo;
    private javax.swing.JRadioButton jrInativo;
    private javax.swing.JTextField jtApelido;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JFormattedTextField jtCep;
    private javax.swing.JTextField jtChapaV;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JFormattedTextField jtCnpj;
    private static javax.swing.JTextField jtCod;
    private javax.swing.JTextField jtCodIbge;
    private javax.swing.JTextField jtCompl;
    private javax.swing.JTextField jtEndWeb;
    private javax.swing.JTextField jtMailCon;
    private javax.swing.JTextField jtNomeCon;
    private javax.swing.JTextField jtNum;
    private javax.swing.JLabel jtPlat;
    private javax.swing.JTextField jtRazaoS;
    private javax.swing.JTextField jtRntrc;
    private javax.swing.JTextField jtRua;
    private javax.swing.JFormattedTextField jtTelCel;
    private javax.swing.JTextField jtTelCon;
    private javax.swing.JFormattedTextField jtTelFixo;
    private javax.swing.JTextField jtiE;
    // End of variables declaration//GEN-END:variables

    //
    public static void recebeidTransportadora(transportadora objtra){
        jtCod.setText(String.valueOf(objtra.getId_transportadora()));
        jtCod.requestFocus();
    }
public void salvar(){
    jbCnpj.setEnabled(true);
    
    jbExcluir.setEnabled(true);
     jbEditar.setEnabled(true);
    jbSalvar.setEnabled(false);
    jbNovo.setEnabled(false);
    
    jtCod.setEnabled(true);
    jbBuscarT.setEnabled(true);
    
    jtCnpj.setEnabled(false);
    jtRazaoS.setEnabled(false);
    jtApelido.setEnabled(false);
    jtiE.setEnabled(false);
    jcPessoa.setEnabled(false);
            jcPlat.setEnabled(false);
            jcEmpi.setEnabled(false);
            
            jrAtivo.setEnabled(false);
            jrInativo.setEnabled(false);
            
           jtCep.setEnabled(false);
    jbCep.setEnabled(false);
    jtCodIbge.setEnabled(false);
    jtCidade.setEnabled(false);
    jcUf.setEnabled(false);
    jtBairro.setEnabled(false);
    jtCompl.setEnabled(false);
    jtNum.setEnabled(false);
    jtRua.setEnabled(false);
    
    jtTelFixo.setEnabled(false);
    jtTelCel.setEnabled(false);
    jtMailCon.setEnabled(false);
    jtEndWeb.setEnabled(false);
    jtNomeCon.setEnabled(false);
    jtRntrc.setEnabled(false);    
    jtTelCon.setEnabled(false);        
    jtChapaV.setEnabled(false); 
    
}

public void novo(){
    
    jbCnpj.setEnabled(true);
    
    jtCnpj.setEnabled(true);
    jtRazaoS.setEnabled(true);
    jtApelido.setEnabled(true);
    jtiE.setEnabled(true);
    jcPessoa.setEnabled(true);
            jcPlat.setEnabled(true);
            jcEmpi.setEnabled(true);
            
            jrAtivo.setEnabled(true);
            jrInativo.setEnabled(true);
            
           jtCep.setEnabled(true);
    jbCep.setEnabled(true);
    jtCodIbge.setEnabled(true);
    jtCidade.setEnabled(true);
    jcUf.setEnabled(true);
    jtBairro.setEnabled(true);
    jtCompl.setEnabled(true);
    jtNum.setEnabled(true);
    jtRua.setEnabled(true);
    
    jtTelFixo.setEnabled(true);
    jtTelCel.setEnabled(true);
    jtMailCon.setEnabled(true);
    jtEndWeb.setEnabled(true);
    jtNomeCon.setEnabled(true);
    jtRntrc.setEnabled(true);    
    jtTelCon.setEnabled(true);        
    jtChapaV.setEnabled(true); 
    
    
    jbEditar.setEnabled(false);
    jbExcluir.setEnabled(false);
    jbNovo.setEnabled(false);
    jbSalvar.setEnabled(true);
    
    jtCod.setEnabled(false);
    jbBuscarT.setEnabled(false);
    
    //
    
    jtCod.setText("");
    jtCnpj.setText("");
    jtRazaoS.setText("");
    jtApelido.setText("");
    jtiE.setText("");
    jcPessoa.setSelectedIndex(0);
            jcPlat.setSelectedIndex(0);
            jcEmpi.setSelectedIndex(0);

            
           jtCep.setText("");
    jtCodIbge.setText("");
    jtCidade.setText("");
    jcUf.setSelectedIndex(0);
    jtBairro.setText("");
    jtCompl.setText("");
    jtNum.setText("");
    jtRua.setText("");
    
    jtTelFixo.setText("");
    jtTelCel.setText("");
    jtMailCon.setText("");
    jtEndWeb.setText("");
    jtNomeCon.setText("");
    jtRntrc.setText("");
    jtTelCon.setText("");        
    jtChapaV.setText("");
    
    
}

public void editar(){
    
    jbCnpj.setEnabled(true);
    
    jtCnpj.setEnabled(true);
    jtRazaoS.setEnabled(true);
    jtApelido.setEnabled(true);
    jtiE.setEnabled(true);
    jcPessoa.setEnabled(true);
            jcPlat.setEnabled(true);
            jcEmpi.setEnabled(true);
            
            jrAtivo.setEnabled(true);
            jrInativo.setEnabled(true);
            
           jtCep.setEnabled(true);
    jbCep.setEnabled(true);
    jtCodIbge.setEnabled(true);
    jtCidade.setEnabled(true);
    jcUf.setEnabled(true);
    jtBairro.setEnabled(true);
    jtCompl.setEnabled(true);
    jtNum.setEnabled(true);
    jtRua.setEnabled(true);
    
    jtTelFixo.setEnabled(true);
    jtTelCel.setEnabled(true);
    jtMailCon.setEnabled(true);
    jtEndWeb.setEnabled(true);
    jtNomeCon.setEnabled(true);
    jtRntrc.setEnabled(true);    
    jtTelCon.setEnabled(true);        
    jtChapaV.setEnabled(true); 
    
    
    jtCod.setEnabled(false);
    jbBuscarT.setEnabled(false);
    
    
    jbSalvar.setEnabled(true);
    jbNovo.setEnabled(false);
    jbEditar.setEnabled(false);
    jbExcluir.setEnabled(true);
    
}

public void cancelar(){
    
    jbCnpj.setEnabled(false);
    
    jbSalvar.setEnabled(false);
    jbEditar.setEnabled(false);
    jbExcluir.setEnabled(false);
    jbNovo.setEnabled(true);
    
     jtCod.setEnabled(true);
    jbBuscarT.setEnabled(true);
    
    jtCnpj.setEnabled(false);
    jtRazaoS.setEnabled(false);
    jtApelido.setEnabled(false);
    jtiE.setEnabled(false);
    jcPessoa.setEnabled(false);
            jcPlat.setEnabled(false);
            jcEmpi.setEnabled(false);
            
            jrAtivo.setEnabled(false);
            jrInativo.setEnabled(false);
            
           jtCep.setEnabled(false);
    jbCep.setEnabled(false);
    jtCodIbge.setEnabled(false);
    jtCidade.setEnabled(false);
    jcUf.setEnabled(false);
    jtBairro.setEnabled(false);
    jtCompl.setEnabled(false);
    jtNum.setEnabled(false);
    jtRua.setEnabled(false);
    
    jtTelFixo.setEnabled(false);
    jtTelCel.setEnabled(false);
    jtMailCon.setEnabled(false);
    jtEndWeb.setEnabled(false);
    jtNomeCon.setEnabled(false);
    jtRntrc.setEnabled(false);    
    jtTelCon.setEnabled(false);        
    jtChapaV.setEnabled(false); 
    
    
    
    jtCod.setText("");
    jtCnpj.setText("");
    jtRazaoS.setText("");
    jtApelido.setText("");
    jtiE.setText("");
    jcPessoa.setSelectedIndex(0);
            jcPlat.setSelectedIndex(0);
            jcEmpi.setSelectedIndex(0);

            
           jtCep.setText("");
    jtCodIbge.setText("");
    jtCidade.setText("");
    jcUf.setSelectedIndex(0);
    jtBairro.setText("");
    jtCompl.setText("");
    jtNum.setText("");
    jtRua.setText("");
    
    jtTelFixo.setText("");
    jtTelCel.setText("");
    jtMailCon.setText("");
    jtEndWeb.setText("");
    jtNomeCon.setText("");
    jtRntrc.setText("");
    jtTelCon.setText("");        
    jtChapaV.setText("");
    
}

public void preencher_objetos(){
       

       objtra.setTra_cnpj(jtCnpj.getText());
       objtra.setTra_razaoS(jtRazaoS.getText());
       objtra.setTra_apelido(jtApelido.getText());
       objtra.setTra_iE(jtiE.getText());
       objtra.setTra_pessoa((String)jcPessoa.getSelectedItem());
       objtra.setTra_plat((String)jcPlat.getSelectedItem());
       objtra.setTra_empi((String)jcEmpi.getSelectedItem());
    
       objtra.setTra_status(status);
       
              objtra.setTra_cep(jtCep.getText());      
  
       objtra.setTra_codIbge(jtCodIbge.getText());
       objtra.setTra_uf((String) jcUf.getSelectedItem());
       objtra.setTra_cidade(jtCidade.getText());
       objtra.setTra_rua(jtRua.getText());
       objtra.setTra_compl(jtCompl.getText());
       objtra.setTra_bairro(jtBairro.getText());
       objtra.setTra_num(jtNum.getText());
       
       objtra.setTra_telCel(jtTelCel.getText());
       objtra.setTra_telFixo(jtTelFixo.getText());
       objtra.setTra_mailCon(jtMailCon.getText());
       objtra.setTra_endWeb(jtEndWeb.getText());
       
       objtra.setTra_veiCon(jtNomeCon.getText());
       objtra.setTra_rntrc(jtRntrc.getText());
       objtra.setTra_veiTel(jtTelCon.getText());
       objtra.setTra_veiChapa(jtChapaV.getText());
       
       
       
   }


public void pesquisaTransportadora(){
    
    
         jtCnpj.setText(objtra.getTra_cnpj().trim());
         jtRazaoS.setText(objtra.getTra_razaoS().trim());
         jtApelido.setText(objtra.getTra_apelido().trim());
         jtiE.setText(objtra.getTra_iE().trim());
         jcPessoa.setSelectedItem(objtra.getTra_pessoa().trim());
         jcPlat.setSelectedItem(objtra.getTra_plat().trim());
         jcEmpi.setSelectedItem(objtra.getTra_empi().trim());
         
          jtCep.setText(objtra.getTra_cep());
         jtCodIbge.setText(objtra.getTra_codIbge());
         jcUf.setSelectedItem(objtra.getTra_uf());
         jtCidade.setText(objtra.getTra_cidade());
         jtRua.setText(objtra.getTra_rua());
         jtCompl.setText(objtra.getTra_compl());
         jtBairro.setText(objtra.getTra_bairro());
         jtNum.setText(objtra.getTra_num());

         jtTelCel.setText(objtra.getTra_telCel());
         jtTelFixo.setText(objtra.getTra_telFixo());
         jtMailCon.setText(objtra.getTra_mailCon());
         jtEndWeb.setText(objtra.getTra_endWeb());
         
         jtNomeCon.setText(objtra.getTra_veiCon());
         jtRntrc.setText(objtra.getTra_rntrc());
         jtTelCon.setText(objtra.getTra_veiTel());
         jtChapaV.setText(objtra.getTra_veiChapa());
         
         
         if (status == 1){
             jrAtivo.setSelected(true);
         }
            if (status == 0){
                jrInativo.setSelected(true);
            }
            
    jbEditar.setEnabled(true);
    jbExcluir.setEnabled(true);
                 
}

public void buscarCep(String cep)
{
     try{
        URL url = new URL("http://viacep.com.br/ws/"+ cep +"/xml");
        SAXReader xml = new SAXReader();
        Document documento = xml.read(url);
        Element root = documento.getRootElement();
        
        for (Iterator<Element> it = root.elementIterator(); it.hasNext();) {
        Element element = it.next();

           // if (jtRuaT3.getText().isEmpty()){
                
            if(element.getQualifiedName().equals("logradouro")){
           jtRua.setText(element.getText().toUpperCase());
            }
            
          //  } if(jtBairroT3.getText().isEmpty()){
                    if(element.getQualifiedName().equals("bairro")){
                  jtBairro.setText(element.getText().toUpperCase());
            }
           // }
            
          //  if (jtCidadeT3.getText().isEmpty()){
                    if(element.getQualifiedName().equals("localidade")){
                  jtCidade.setText(element.getText().toUpperCase());
            }
           // }
            
                     if(element.getQualifiedName().equals("uf")){
                  jcUf.setSelectedItem(element.getText());
           }
                    if(element.getQualifiedName().equals("ibge")){
                  jtCodIbge.setText(element.getText());
    }
        
        }
    }catch(Exception e){
            
                    System.err.println("Erro: "+ e);
    }

}

public ConsultaCNPJController getController() {
		if (controller == null) {
			controller = new ConsultaCNPJController();
		}
		return controller;
	}

public void buscarCNPJ (){
              String cnpj = jtCnpj.getText();
				cnpj = cnpj.replaceAll("[^0123456789]", "");
				try {
					PessoaJuridica pessoa = getController().consulta(cnpj);
					
					if (pessoa != null) {
                                            
						
                                                    jcUf.setSelectedItem(pessoa.getEstado().toUpperCase());
                                                    jtRazaoS.setText(pessoa.getRazaoSocial().toUpperCase());
                                                    jtBairro.setText(pessoa.getBairro().toUpperCase());
                                                    jtRua.setText(pessoa.getRua().toUpperCase());
                                                    jtNum.setText(pessoa.getNumero());
                                                    jtTelFixo.setText(pessoa.getTelefone());
                                                    jtCep.setText(pessoa.getCep());
                                                    jtCompl.setText(pessoa.getComplemento().toUpperCase());
                                                    jtMailCon.setText(pessoa.getEnderecoEletronico());
                                                    jtCidade.setText(pessoa.getMunicipio().toUpperCase());
                                                    
                                                    if (pessoa.getSituacao().equals("ATIVA")){
             jrAtivo.setSelected(true);
         }
            else{
                jrInativo.setSelected(true);
            }
                                                    
					}                           
                                        
					
				} catch (Exception e) {
					JOptionPane.showMessageDialog(this, "CNPJ n�o encontrado.");
				}
			}
}
